DROP TABLE IF EXISTS Current_Magnetic_Field CASCADE;
DROP TABLE IF EXISTS specialist_monolith_isledovaniya CASCADE;
DROP TABLE IF EXISTS generator_monolith CASCADE;
DROP TABLE IF EXISTS Currents CASCADE;
DROP TABLE IF EXISTS Magnetic_Fields CASCADE;
DROP TABLE IF EXISTS specialist_isledovaniya CASCADE;
DROP TABLE IF EXISTS Material CASCADE;
DROP TABLE IF EXISTS Monolith CASCADE;

